r"""Tests for worldkernels/_version.py (auto-generated by setuptools_scm)."""

from __future__ import annotations


def test_version_tuple_matches_string():
    from worldkernels._version import __version__, __version_tuple__

    assert isinstance(__version__, str)
    assert isinstance(__version_tuple__, tuple)
    assert len(__version_tuple__) >= 3
